### ISSUE TITLE
This stuffs pasted

### ISSUE THREAD

**Issue by windows-fryer** [SHIDWORD/cs2-project#1]
All stolen from ligaware.

**Comment by SHIDWORD** [comment]
Sorry but [#1586](https://github.com/ocornut/imgui/issues/1586)

**Comment by lordraiden23** [comment]
Who told u that its stolen? You did nun yourself but spitting straight bullshit. i'd shoot u down irl for such behavior.
SHIDWORD is a god . Hope to see his project penetrate skeet and others 😄

**Comment by windows-fryer** [comment]
Please don't kill me I'm sorry...

**Comment by lordraiden23** [comment]
> Please don't kill me I'm sorry...

Ok sorry that was too much just had an angry mood....anyways thank to this guy he really helps the community not to die and develop : P

**Comment by CoconutCoder1** [comment]
where is the hitchance feature?

**Comment by SHIDWORD** [comment]
in pAimbot.h Sir

**Comment by CoconutCoder1** [comment]
im not see a pAimbot.h on files
